cadastros/urls.py
from django.urls import path

from .views import(
                    usuario,
                    cria_usuario,
                    )

app_name = 'cadastro'

urlpatterns = [
    path('usuario', usuario, name='usuario'),
    path('usuario/criar', cria_usuario, name='cria_usuario'),
]

finan/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

fluxo/urls.py
from django.urls import path

from .views import(
                    inicio, 
                    adicionar_lancamento,
                    lancamentos, 
                    editar_lancamento,
                    filtros,
                    cadastro_categoria,
                    cadastro_conta,
                    cadastro_cliente_fornecedor,
                    cadastro_centro_custo,
                    login_view,
                    logout_view,
                    transferir,
                    relatorio_fluxo,
                    relatorio_lancamentos,
                    exportar_relatorio_excel,
                    )

app_name = 'fluxo'

urlpatterns = [    
    path('adicionar/<str:tipo>/', adicionar_lancamento, name='adicionar_lancamento'),
    path('editar/<str:tipo>/<int:ad>/<int:id>/', editar_lancamento, name='editar_lancamento'),
    path('transferir/', transferir, name='transferir'),
    path('cadastro/categoria/', cadastro_categoria, name='cadastro_categoria'),
    path('cadastro/conta/', cadastro_conta, name='cadastro_conta'),
    path('cadastro/centro-custo/', cadastro_centro_custo, name='cadastro_centro_custo'),
    path('cadastro/<str:tipo>/', cadastro_cliente_fornecedor, name='cadastro_cliente_fornecedor'),
    path('filtros/', filtros, name='filtros'),
    path('relatorios/fluxo/', relatorio_fluxo, name='relatorio_fluxo'),
    path('relatorios/lancamentos/', relatorio_lancamentos, name='relatorio_lancamentos'),
    path('relatorio-lancamentos/exportar/', exportar_relatorio_excel, name='exportar_relatorio_excel'),
    path('lancamentos/<str:filtro>/', lancamentos, name='lancamentos'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', inicio, name='inicio'),
]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from fluxo import views

urlpatterns = [
    path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
    path('cadastro/', include('cadastros.urls')),
    path('', include('fluxo.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finan/models.py
from django.db import models
from colorfield.fields import ColorField
from utils.rands import slugify_new, random_color

class Categoria(models.Model):
    class Meta:
        ordering = ['descricao']

    MISTA = 'MI'
    DESPESA = 'DE'
    RECEITA = 'RE'
    CLASSIFICACAO_ESCOLHAS = {
        MISTA: 'Mista',
        DESPESA: 'Despesa',
        RECEITA: 'Receita',
    }
    descricao = models.CharField(verbose_name='descricao', max_length=200, default='')
    cor = ColorField(auto_created=True, max_length=7)
    ativo = models.BooleanField(default=True)
    is_categoria_filha = models.BooleanField(verbose_name='Categoria filha', default=False)
    slug = models.SlugField(
        unique=True, default=None,
        blank=True, max_length=255,
    )
    categoria_pai = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Categoria pai',
    )
    classificacao = models.CharField(
        max_length=3,
        choices=CLASSIFICACAO_ESCOLHAS,
        default=MISTA,
    )
    data_criada = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.descricao, 4)
        if self.cor == '#FFFFFF':
            self.cor = random_color()
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.descricao)


class Empresa(models.Model):
    class Meta:
        verbose_name_plural = "Minha empresa"
        
    logotipo = models.ImageField(upload_to='logotipos/', blank=True, null=True)
    nome_fantasia = models.CharField('nome fantasia', max_length=100)
    razao_social = models.CharField('razao social', max_length=100)
    cnpj_cpf = models.CharField('CPF/CNPJ', max_length=14)
    insc_estadual = models.CharField('I.E.', max_length=18, blank=True, null=True)
    insc_municipal = models.CharField('I.M.', max_length=18, blank=True, null=True)
    endereco = models.CharField(max_length=200)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    cep = models.CharField(max_length=9)
    telefone = models.CharField(max_length=15)
    site_empresa = models.URLField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=254)
    setor_empresa = models.CharField(max_length=100)
    ramo_atuacao = models.CharField(max_length=100)
    produtos_servicos = models.TextField()
    numero_empregados = models.IntegerField()
    data_criacao = models.DateField()

    def __str__(self):
        return self.nome_fantasia

class Conta(models.Model):
    TIPO_CONTA_CHOICES = (
        ('Conta Corrente', 'Conta Corrente'),
        ('Poupança', 'Poupança'),
    )

    TIPO_CHAVE_PIX_CHOICES = (
        ('CPF/CNPJ', 'CPF/CNPJ'),
        ('E-mail', 'E-mail'),
        ('Telefone', 'Telefone'),
        ('Aleatória', 'Aleatória'),
    )

    tipo_conta = models.CharField(max_length=20, choices=TIPO_CONTA_CHOICES)
    banco = models.CharField(max_length=100)
    agencia = models.CharField(max_length=10)
    conta = models.CharField(max_length=15)
    gerente = models.CharField(max_length=100)
    telefone = models.CharField(max_length=15)
    apelido_conta = models.CharField(max_length=150)
    data_inicio = models.DateField()
    saldo_inicial = models.DecimalField(max_digits=15, decimal_places=2)
    saldo_conta = models.DecimalField(max_digits=15, decimal_places=2)  # Ajustado max_digits
    tipo_chave_pix = models.CharField(max_length=20, choices=TIPO_CHAVE_PIX_CHOICES)  # Corrigido para usar choices
    chave_pix = models.CharField(max_length=100)
    situacao_conta = models.CharField(max_length=100)
    agrupamento = models.CharField(max_length=100)
    permite_lancamentos = models.BooleanField()
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.apelido_conta


class CentroCusto(models.Model):
    TIPO_CENTRO_CHOICES = (
        ('Centro de custo/lucro pai', 'Centro de custo/lucro pai'),
        ('Centro de custo/lucro filho', 'Centro de custo/lucro filho'),
    )
    descricao = models.CharField(verbose_name='descricao', max_length=200, default='')
    tipo_centro_custo = models.CharField(max_length=100, choices=TIPO_CENTRO_CHOICES)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.descricao

class FormaPagamento(models.Model):
    descricao = models.CharField(verbose_name='descricao', max_length=200, default='')
    ativa = models.BooleanField(default=True)

    def __str__(self):
        return self.descricao

class Tag(models.Model):
    tag = models.CharField(verbose_name='tags', max_length=100)

    def __str__(self):
        return self.tag

fluxo/views/adicionar_lancamento.py
from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from fluxo.forms import (
                    LancamentosObForm, 
                    AnexoForm, ItemForm, 
                    )

@login_required
def adicionar_lancamento(request, tipo):

    if request.method == 'POST':
        valor = request.POST['valor']
        valor = float(valor.replace('.', '').replace(',', '.'))
        if tipo == 'DESPESA':
            valor *= -1
        valor = f'{valor:.2f}'

        valores = request.POST.copy()
        valores['valor'] = valor
        valores['tipo'] = tipo
        valores['valor_total'] = 0

        lancamentoForm = LancamentosObForm(valores)
        itemForm = ItemForm(valores)
        anexoForm = AnexoForm(request.POST, request.FILES)
        valor_parcelado = None
        if request.POST['parcelas']:
            parcelas = int(request.POST['parcelas'])
            if parcelas > 1:
                valor_parcelado = Decimal(valor) / parcelas

        if valor_parcelado and not 'salvar_itens' in request.POST:
            data_lancamento = datetime.strptime(valores['data_lancamento'], '%Y-%m-%d').date()
            for i in range(parcelas):
                lancamentoForm = LancamentosObForm(valores)
                itemForm = ItemForm(valores)
                anexoForm = AnexoForm(request.POST, request.FILES)

                if lancamentoForm.is_valid():
                    lancamento = lancamentoForm.save(commit=False)
                    if i > 0:
                        data_lancamento += timedelta(days=30)
                        lancamento.data_lancamento = data_lancamento
                    lancamento.save()
                    valores['lancamento'] = lancamento.id
                    itemForm = ItemForm(valores)
                    
                    if itemForm.is_valid():
                        item = itemForm.save(commit=False)
                        item.lancamento = lancamento
                        item.valor = valor_parcelado
                        item.descricao = f'{item.descricao} {i + 1} de {parcelas}'
                        lancamento.valor_total = item.valor
                        item.save()
                        lancamento.save()
                        
                    if anexoForm.is_valid():
                        arquivos = anexoForm.save(commit=False)
                        arquivos.lancamento = lancamento
                        arquivos.save()

        else:
            if lancamentoForm.is_valid():
                lancamento = lancamentoForm.save()
                valores['lancamento'] = lancamento.id
                itemForm = ItemForm(valores)
                if itemForm.is_valid():
                    item = itemForm.save(commit=False)
                    item.lancamento = lancamento
                    lancamento.valor_total = item.valor
                    item.save()
                    lancamento.save()

                if anexoForm.is_valid():
                    arquivos = anexoForm.save(commit=False)
                    arquivos.lancamento = lancamento
                    arquivos.save()

        if 'salvar_anexo' in request.POST:
            return redirect(f'/editar/{tipo}/0/{lancamento.id}')
        elif 'salvar_itens' in request.POST:
                adiciona_itens = True
                return redirect(f'/editar/{tipo}/1/{lancamento.id}')
        else:
            return redirect('/lancamentos/todos/')
            
    else:
        lancamentoForm = LancamentosObForm()
        itemForm = ItemForm()
        anexoForm = AnexoForm()

    context = {
        'tipo': tipo.capitalize(),
        'simbolo': '+' if tipo == 'RECEITA' else '-',
        'cor': 'text-primary' if tipo == 'RECEITA' else 'text-danger',
        'titulo': f'Adicionar {tipo.lower()}',
        'tipo1': 'Recebido' if tipo == 'RECEITA' else 'Pago',
        'tipo2': 'À receber' if tipo == 'RECEITA' else 'À pagar',
        'lancamentoForm': lancamentoForm,
        'itemForm': itemForm,
        'anexoForm': anexoForm,
        'adiciona_lancamento': True,
    }

    return render(request, 'ad_lancamento.html', context)

fluxo/views/exporta_excel.py
from django.http import HttpResponse
from openpyxl import Workbook
from datetime import datetime
from django.contrib.auth.decorators import login_required
from datetime import datetime, date, timedelta
from fluxo.models import Item

@login_required
def exportar_relatorio_excel(request):
    # Recupera os dados da sessão ou aplica os mesmos filtros usados na view
    data_inicio = request.session.get('data_inicio', None)
    data_fim = request.session.get('data_fim', None)
    categoria_selecionada = request.GET.get('categoria', None)

    # Converte strings para objetos de data
    if isinstance(data_inicio, str):
        data_inicio = datetime.strptime(data_inicio, '%Y-%m-%d').date()
    if isinstance(data_fim, str):
        data_fim = datetime.strptime(data_fim, '%Y-%m-%d').date()

    if not data_inicio or not data_fim:
        data_inicio = datetime.now().date() - timedelta(days=30)
        data_fim = datetime.now().date()

    # Filtra os lançamentos
    lancamentos_list = Item.objects.filter(
        lancamento__data_lancamento__range=(data_inicio, data_fim),
        lancamento__situacao='PAGO'
    ).order_by("lancamento__data_lancamento", "lancamento__pk")

    if categoria_selecionada:
        lancamentos_list = lancamentos_list.filter(categoria_id=categoria_selecionada)

    # Cria um novo arquivo Excel
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Relatório de Lançamentos"

    # Cabeçalhos da tabela
    sheet.append(["Data Lançamento", "Categoria", "Descrição", "Valor"])

    # Preenche os dados na planilha
    for item in lancamentos_list:
        sheet.append([
            item.lancamento.data_lancamento.strftime('%d-%m-%Y') if item.lancamento.data_lancamento else '',
            item.categoria.descricao if item.categoria else '',
            item.descricao,
            item.valor,
        ])

    # Configura a resposta HTTP
    response = HttpResponse(
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
    response["Content-Disposition"] = 'attachment; filename="relatorio_lancamentos.xlsx"'

    # Salva o arquivo Excel na resposta
    workbook.save(response)
    return response

fluxo/views/inicio.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from fluxo.models import Lancamento, Item
from finan.models import Conta
from django.db.models import Sum
from datetime import date, timedelta

@login_required
def inicio(request):

    # Obtém a data de início e fim do mês atual
    hoje = date.today()
    data_inicio = date(hoje.year, hoje.month, 1)

    # Calcula a data do primeiro dia do próximo mês
    if hoje.month == 12:  # Se for dezembro, o próximo mês é janeiro do próximo ano
        data_fim = date(hoje.year + 1, 1, 1) - timedelta(days=1)
    else:
        data_fim = date(hoje.year, hoje.month + 1, 1) - timedelta(days=1)
        
    apagar = Lancamento.objects.filter(
        data_lancamento__range=(data_inicio, data_fim)
    ).order_by("data_lancamento", "pk").prefetch_related('itens').filter(situacao='APAGAR')

    # apagar = Lancamento.objects.all().filter(situacao='APAGAR').order_by('data_lancamento')[:10]

    lista_saldos =[]
    for i in Conta.objects.all():
        # saldo = Lancamento.objects.all().filter(
        #                     conta_id=i.id, situacao='PAGO').aggregate(Sum('valor_total'))['valor_total__sum']
        saldo = Item.objects.all().filter(lancamento__conta_id=i.id, lancamento__situacao='PAGO').aggregate(Sum('valor'))['valor__sum']
        if saldo is None:
            saldo = 0
        conta_saldo = {
                        'apelido':i.apelido_conta,
                        'saldo': saldo,
               }
        lista_saldos.append(conta_saldo)

    saldo_total = 0

    for i in lista_saldos:
        saldo_total += i['saldo']

    context = {
        'is_inicio': True,
        'apagar': apagar,
        'lista_saldos': lista_saldos,
        'saldo_total': saldo_total,
    }

    return render(
        request,
        'inicio.html',
        context
    )

fluxo/views/login.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')  # Redirecione para a página inicial ou outra página desejada
        else:
            messages.error(request, 'Usuário ou senha inválidos')
    return render(request, 'login.html')

fluxo/views/logout.py
from django.contrib.auth import logout
from django.shortcuts import redirect


def logout_view(request):
    logout(request)
    return redirect('/login/')

fluxo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static 'fluxo/bootstrap/css/form-validation.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="icon" href="{% static 'bootstrap/favicon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static "fluxo/css/fluxo.css" %}">

    <title>Finan - {{titulo}}</title>
    <style>
        #inputField {
            display: none;
        }
        .select2-selection {
            height: 37px !important;
            border-color: #ced4da !important;
            margin-top: 0.3%;
        }
    </style>
</head>

<body class="bg-light">

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url "fluxo:inicio" %}">Finan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            {% if is_inicio %}
                <li class="nav-item active">
            {% else %}
                <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url "fluxo:inicio" %}">Início</a>
                </li>
            {% if is_lancamento %}
                <li class="nav-item active">
            {% else %}
                <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url "fluxo:lancamentos" filtro='todos' %}">Lançamentos</a>
                </li>
            {% if is_relatorios %}
                <li class="nav-item dropdown active">
            {% else %}
                <li class="nav-item dropdown">
            {% endif %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Relatórios
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url "fluxo:relatorio_fluxo" %}">Fluxo de caixa</a>
                  <a class="dropdown-item" href="{% url "fluxo:relatorio_lancamentos" %}">Lançamentos</a>
                </div>
              </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <div class="col-6 dropdown">
                <a class="btn btn-outline-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Cadastros
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url "fluxo:cadastro_conta" %}">Conta</a>
                    <a class="dropdown-item" href="{% url "fluxo:cadastro_categoria" %}">Categorias</a>
                    <a class="dropdown-item" href="{% url "fluxo:cadastro_centro_custo" %}">Centro de Custo</a>
                    <a class="dropdown-item" href="{% url "fluxo:cadastro_cliente_fornecedor" tipo='FORNECEDOR'%}">Fornecedor</a>
                    <a class="dropdown-item" href="{% url "fluxo:cadastro_cliente_fornecedor" tipo='CLIENTE'%}">Cliente</a>
                    <a class="dropdown-item" href="{% url "cadastro:usuario" %}">Usuário</a>
                </div>
            </div>
        </form>
        <form class="form-inline mt-2 mt-md-0">
            <div class='col'>
            <a class="btn btn-outline-light my-2 my-sm-0" href="{% url 'fluxo:logout' %}">Sair</a>
            </div>
        </form>
        </div>
    </nav>
</header>

    {% block conteudo %}{% endblock conteudo %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        (function() {
        'use strict';

        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');

            var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
                }
                form.classList.add('was-validated');
            }, false);
            });
        }, false);
        })();
    </script>
    <script src="https://igorescobar.github.io/jQuery-Mask-Plugin/js/jquery.mask.min.js"></script>

    {% block scripts %}{% endblock scripts %}

</body>
</html>

fluxo/templates/cad_categoria.html
{% extends 'base.html' %}
{% load static %}


{% block conteudo %}

<main role="main" class="flex-shrink-0">
    <br>
    <div class="container py-5">
    <h3 class='text-center'>{{ titulo }}</h3>
    <br>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

fluxo/templates/cad_centro_custo.html
{% extends 'base.html' %}
{% load static %}


{% block conteudo %}

<main role="main" class="flex-shrink-0">
    <br>
    <div class="container py-5">
    <h3 class='text-center'>{{ titulo }}</h3>
    <br>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

fluxo/templates/cad_cliente_fornecedor.html
{% extends 'base.html' %}
{% load static %}


{% block conteudo %}

<main role="main" class="flex-shrink-0">
    <br>
    <div class="container py-5">
        <h3 class='text-center'>{{ titulo }}</h3>
        <br>
        <form method="post" novalidate>
            {% csrf_token %}
                <div class="col-md-12">  
                    <div class="row">          
                        {% for field in form  %}
                            <div class="col-md-6">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                                {% endif %}
                            </div>
                        {% endfor %}                        
                    </div>
                    <div class='row'>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </div>
        </form>
    </div>

{% endblock %}

fluxo/templates/cad_conta.html
{% extends 'base.html' %}
{% load static %}


{% block conteudo %}

<main role="main" class="flex-shrink-0">
    <br>
    <div class="container py-5">
    <h3 class='text-center'>{{ titulo }}</h3>
    <br>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

fluxo/templates/filtros.html
{% extends 'base.html' %}
{% load static %}


{% block conteudo %}

<div class="starter-template">
FILTROS
</div>

{% endblock %}

fluxo/templates/inicio.html
{% extends 'base.html' %}
{% load static %}
{% load currency_filters %}


{% block conteudo %}

<br>
<div class="container py-5">
<div class="row">
    <div class="col-sm-6 mb-2">
      <div class="card">
        <div class="card-header">Saldo Contas</div>
        <div class="card-body">
          <table class="table table-sm table-borderless">
            <thead>
              <tr>
                <th class="text-dark" scope="col">Conta</th>
                <th class="text-right text-dark" scope="col">Saldo</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for conta in lista_saldos %}
              <tr>
                <th class="text-info"scope="row">{{conta.apelido}}</th>
                <td class="text-right text-info">{{conta.saldo|currency}}</td>
                <td></td>
                <td></td>
              </tr>
              {% endfor %}
              <tr>
                <th class="text-dark" scope="col">Saldo Total</th>
                <th class="text-right text-dark" scope="col">{{ saldo_total|currency }}</th>
                <th></th>
                <th></th>
              </tr>
            </tbody>
          </table>
            <a href="{% url "fluxo:lancamentos" filtro='todos' %}" class="btn btn-primary">Ir Lançamentos</a>
        </div>
      </div>
    </div>
    <div class="col-sm-6 mb-2">
      <div class="card">
        <div class="card-header">Contas a Pagar</div>
        <div class="card-body">
            <table class="table table-sm table-borderless">
              <thead>
                <tr>
                  <th scope="col">Data</th>
                  <th class="text-dark" scope="col">Descrição</th>
                  <th class="text-right text-dark" scope="col">Valor</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for conta in apagar %}
                <tr>
                  <th class="text-info" scope="row">{{conta.data_lancamento|date:"d M"}}</th>
                  <td class="text-info" >
                    <a class="text-info" href="{% url 'fluxo:editar_lancamento' tipo=conta.tipo id=conta.id ad='0' %}">
                    {{conta.itens.first.descricao|truncatechars:30}}
                    </a>
                  </td>
                  <td class="text-right text-danger">{{conta.valor_total|currency}}</td>
                  <td></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
              <a href="{% url "fluxo:lancamentos" filtro='apagar' %}"class="btn btn-primary">Contas a pagar</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}